apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotting-service-deployment
  labels:
    app: plotting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plotting-service
  template:
    metadata:
      labels:
        app: plotting-service
    spec:
      containers:
      - name: plotting-service
        image: parnal/codist-plotting:amd64
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        env:
        - name: CLOUDINARY_CLOUD_NAME
          value: dzlhjgubi
        - name: CLOUDINARY_API_KEY
          value: "198111863142296"
        - name: CLOUDINARY_API_SECRET
          value: _WfyYti9RBjF9xWnN89CA8Uvbg0
---
apiVersion: v1
kind: Service
metadata:
  name: plotting-service
spec:
  selector:
    app: plotting-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
    nodePort: 30000